- README.md
> добавил имя

- index.html
> добавил своё имя Лева

- index.html
> добавил свое имя Борис

- Boris/boris.html
> add tamplate

- css/zorbrith22.css
- zorbrith22/zorbrith22.html
добавил цвет и что-то наверное я не помню
> добавил бесплатный вай-фай:D

- Boris/boris.html
- css/boris.css
> изменил файлы    css/boris.css -   Boris/boris.html

- Boris/boris.html
> поработал над оформлением

- css/zorbrith22.css
- zorbrith22/zorbrith22.html
> изменил zorbrith22.css и zorbrith.html

- zorbrith22/zorbrith22.html
> изменил свой html

- Boris/boris.html
> изменил навигацию

- Boris/boris.html
> исправил ошибки

- Boris/boris.html
> удалил ненужное

- css/zorbrith22.css
скопировал и вставил с leonid.css в свой css
> изменил свой css

- css/sofia.css
> изменила css

- Boris/boris.html
> поработал над разделами

- Boris/boris.html
- js/boris.js
> добавил пот

- Boris/boris.html
- css/boris.css
- js/boris.js
> добавил всплываюшее окно

- Boris/boris.html
> переделал код под себя

- Boris/boris.html
> на проверку

- js/zorbrith22.js
- lev/zorbrith22.html
> изменил свой js и html

- Boris/boris.html
- css/boris.css
- js/boris.js
> доработал код

- Boris/boris.html
- css/boris.css
- js/boris.js
> доработал кнопки

- Boris/boris.html
- css/boris.css
добавил дополнительную информацию о играх
> добавил дополнительную информацию

- Boris/boris.html
- css/boris.css
доработал сайт или ничё не успел
> доработал сайт или ничё не успел

- Boris/boris.html
все испортил но и не много исправил
> все испортил но и не много исправил

- Boris/boris.html
<div class="row mb-2 r1">
<div class="col-md-6">
<div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
<div class="col p-4 d-flex flex-column position-static">
<h3 class="mb-0">Descenders</h3>
<p class="card-text mb-auto">Это гоночный спортивный симулятор, в котором игроки состязаются в гонках на спортивных велосипедах.</p>
<button id="desc">Подробнее...</button>
</div>
<div class="col-auto d-none d-lg-block">
<svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" …
> ничо не сделал

- Boris/boris.html
- js/boris.js
> ничиго не сделал
